//! Chwazi-style random finger picker.
//!
//! Everyone puts a finger on the screen; after a short still moment the app
//! randomly chooses one finger, an order, or splits everyone into teams.
//!
//! Rendered on a full-screen `<canvas>` driven by pointer events, so it works
//! with real multi-touch on phones/tablets and with a mouse on desktop.
//!
//! The code is split into small modules:
//! - [`config`] — tunable constants and the colour palette.
//! - [`state`] — the `App`/`Finger` state types shared across the modules.
//! - [`input`] — pointer/UI events and the state transitions they drive.
//! - [`sim`] — geometry helpers, the per-frame update, and the random pick.
//! - [`render`] — all canvas drawing.
//! - [`util`] — DOM/rAF glue, easing, RNG, and colour helpers.

mod config;
mod input;
mod render;
mod sim;
mod state;
mod util;

use std::collections::HashMap;

use wasm_bindgen::prelude::*;
use wasm_bindgen::JsCast;
use web_sys::{CanvasRenderingContext2d, HtmlCanvasElement, HtmlElement};

use crate::input::{install_pointer_handlers, install_ui_handlers, install_window_handlers};
use crate::state::{App, Mode, Phase, APP};
use crate::util::{document, start_raf};

// ---------------------------------------------------------------------------
// Entry point (called by the wasm-bindgen init generated by Trunk)
// ---------------------------------------------------------------------------

#[wasm_bindgen(start)]
pub fn start() -> Result<(), JsValue> {
    let document = document();
    let canvas = document
        .get_element_by_id("c")
        .unwrap()
        .dyn_into::<HtmlCanvasElement>()?;
    let ctx = canvas
        .get_context("2d")?
        .unwrap()
        .dyn_into::<CanvasRenderingContext2d>()?;
    let ui = document
        .get_element_by_id("ui")
        .unwrap()
        .dyn_into::<HtmlElement>()?;
    let gcount_el = document
        .get_element_by_id("gcount")
        .unwrap()
        .dyn_into::<HtmlElement>()?;
    let dots_el = document
        .get_element_by_id("dots")
        .unwrap()
        .dyn_into::<HtmlElement>()?;
    let dcount_el = document
        .get_element_by_id("dcount")
        .unwrap()
        .dyn_into::<HtmlElement>()?;

    let mut app = App {
        canvas: canvas.clone(),
        ctx,
        ui,
        gcount_el,
        dots_el,
        dcount_el,
        fingers: HashMap::new(),
        phase: Phase::Idle,
        mode: Mode::One,
        groups: 2,
        next_virt: -1,
        now: 0.0,
        last_t: 0.0,
        width: 0.0,
        height: 0.0,
        dpr: 1.0,
        winner: None,
        reveal: 0.0,
        spin: 0.0,
        flood_col: None,
        flood_pos: None,
        cancel: None,
    };
    app.resize();
    APP.with(|a| *a.borrow_mut() = Some(app));

    install_pointer_handlers(&canvas);
    install_ui_handlers()?;
    install_window_handlers();
    start_raf();
    Ok(())
}
